### ISSUE TITLE
Switch to SecureRandom for enhanced security

### ISSUE THREAD

**Issue by MasterFlomaster1** [9winged/KiKi-easy-password-generator#1]
Consider using `SecureRandom` instead of `Random`. `SecureRandom` uses cryptographically strong algorithms (such as SHA1PRNG or NativePRNG) that are harder to predict, making them suitable for cryptographic purposes like generating keys, creating random secrets, etc.

**Comment by 9winged** [comment]
Thank you for the feedback, I appreciate it! That sounds like a big upgrade to the existing code. I'll implement it soon.

**Comment by MasterFlomaster1** [comment]
closed in 53acc83
